//! Database-backed MemoryLayer implementations (#83).
//!
//! Wraps PostgreSQL repositories (LTM, STM, KG, MM) behind the `MemoryLayer`
//! trait so the `MemoryKernel` → `MemoryAgent` path shares the same
//! persistence, RLS, outbox, and audit semantics as the production
//! REST/MCP/A2A paths.
//!
//! The in-memory layers (`ltm_layer`, `stm_layer`, etc.) remain as test-only
//! backends. Production code should use the database-backed layers below.

use crate::db::{kg::KGRepository, ltm::LTMRepository, mm::MMRepository, pool, stm::STMRepository};
use crate::kernel::error::{MemoryError, MemoryResult};
use crate::kernel::traits::{LayerStats, MemoryLayer};
use crate::kernel::types::*;
use crate::tenant::TenantId;

// ============================================================================
// LTM Database Layer
// ============================================================================

pub struct DatabaseLtmLayer {
    tenant_id: TenantId,
}

impl DatabaseLtmLayer {
    pub fn new(tenant_id: TenantId) -> Self {
        Self { tenant_id }
    }
}

#[async_trait::async_trait]
impl MemoryLayer for DatabaseLtmLayer {
    fn layer_type(&self) -> LayerType {
        LayerType::Ltm
    }

    async fn store(&self, entry: MemoryEntry) -> MemoryResult<MemoryId> {
        let content = text_content(&entry.content)?;
        let title = entry.metadata.tags.first().map(|s| s.as_str());
        let source_id = entry
            .metadata
            .source
            .as_deref()
            .unwrap_or("kernel_store");
        let source_type = entry.metadata.extra.get("source_type")
            .and_then(|v| v.as_str())
            .unwrap_or("memory");
        let entry_id = LTMRepository::create_knowledge_entry(
            &self.tenant_id,
            source_id,
            source_type,
            title,
            &content,
            "text",
            &[], // embedding is generated by outbox
            "unknown",
            0,
            Some(entry.metadata.importance),
        )
        .await
        .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(MemoryId::from_string(entry_id))
    }

    async fn retrieve(&self, id: &MemoryId) -> MemoryResult<MemoryEntry> {
        let entry = LTMRepository::get_entry_by_id(&pool(), &self.tenant_id, id.as_str())
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        match entry {
            Some(e) => Ok(MemoryEntry {
                id: MemoryId::from_string(e.entry_id),
                layer: LayerType::Ltm,
                content: MemoryContent::Text(e.content),
                metadata: MemoryMetadata {
                    source: Some(e.source_id),
                    tags: e.title.into_iter().collect(),
                    importance: 0.5,
                    ..Default::default()
                },
                created_at: chrono::DateTime::parse_from_rfc3339(&e.created_at)
                    .map(|d| d.timestamp())
                    .unwrap_or(0),
                updated_at: chrono::DateTime::parse_from_rfc3339(&e.updated_at)
                    .map(|d| d.timestamp())
                    .unwrap_or(0),
            }),
            None => Err(MemoryError::NotFound(format!(
                "LTM entry not found: {}",
                id.as_str()
            ))),
        }
    }

    async fn search(&self, query: &MemoryQuery) -> MemoryResult<Vec<MemoryMatch>> {
        let response = LTMRepository::list_entries(
            &pool(),
            &self.tenant_id,
            None,
            None,
            Some(query.limit as i32),
            Some(query.offset as i32),
        )
        .await
        .map_err(|e| MemoryError::Storage(e.to_string()))?;
        let query_text = query.text.as_deref().unwrap_or("").to_lowercase();
        Ok(response
            .entries
            .into_iter()
            .filter(|e| {
                if query_text.is_empty() {
                    true
                } else {
                    e.content.to_lowercase().contains(&query_text)
                }
            })
            .map(|e| MemoryMatch {
                entry: MemoryEntry {
                    id: MemoryId::from_string(e.entry_id),
                    layer: LayerType::Ltm,
                    content: MemoryContent::Text(e.content),
                    metadata: MemoryMetadata::default(),
                    created_at: 0,
                    updated_at: 0,
                },
                score: 0.5,
                highlights: vec![],
            })
            .collect())
    }

    async fn update(&self, id: &MemoryId, entry: MemoryEntry) -> MemoryResult<()> {
        let content = text_content(&entry.content)?;
        LTMRepository::update_entry(&self.tenant_id, id.as_str(), None, Some(&content), None)
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(())
    }

    async fn delete(&self, id: &MemoryId) -> MemoryResult<()> {
        LTMRepository::soft_delete_entry(&pool(), &self.tenant_id, id.as_str())
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(())
    }

    async fn stats(&self) -> MemoryResult<LayerStats> {
        let count = LTMRepository::count(&pool(), &self.tenant_id)
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(LayerStats {
            entry_count: count as usize,
            size_bytes: 0,
            avg_access_count: 0.0,
        })
    }
}

// ============================================================================
// STM Database Layer
// ============================================================================

pub struct DatabaseStmLayer {
    tenant_id: TenantId,
}

impl DatabaseStmLayer {
    pub fn new(tenant_id: TenantId) -> Self {
        Self { tenant_id }
    }
}

#[async_trait::async_trait]
impl MemoryLayer for DatabaseStmLayer {
    fn layer_type(&self) -> LayerType {
        LayerType::Stm
    }

    async fn store(&self, entry: MemoryEntry) -> MemoryResult<MemoryId> {
        let content = text_content(&entry.content)?;
        let user_id = entry.metadata.user_id.as_deref().unwrap_or("unknown");
        let agent_id = entry.metadata.agent_id.as_deref().unwrap_or("unknown");
        let session_id = STMRepository::create_session(
            &self.tenant_id,
            user_id,
            agent_id,
            "memory_store",
            4000,
            24,
        )
        .await
        .map_err(|e| MemoryError::Storage(e.to_string()))?;
        STMRepository::add_message(&pool(), &self.tenant_id, &session_id, "user", &content, None, None)
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(MemoryId::from_string(session_id))
    }

    async fn retrieve(&self, id: &MemoryId) -> MemoryResult<MemoryEntry> {
        let session = STMRepository::get_session(&pool(), &self.tenant_id, id.as_str())
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        match session {
            Some(s) => {
                let sid = s.session_id.clone();
                Ok(MemoryEntry {
                    id: MemoryId::from_string(sid.clone()),
                    layer: LayerType::Stm,
                    content: MemoryContent::Json(serde_json::to_value(&s).unwrap_or_default()),
                    metadata: MemoryMetadata {
                        user_id: Some(s.user_id),
                        session_id: Some(sid),
                        agent_id: Some(s.agent_id),
                        ..Default::default()
                    },
                    created_at: chrono::DateTime::parse_from_rfc3339(&s.created_at)
                        .map(|d| d.timestamp())
                        .unwrap_or(0),
                    updated_at: 0,
                })
            }
            None => Err(MemoryError::NotFound(format!(
                "STM session not found: {}",
                id.as_str()
            ))),
        }
    }

    async fn search(&self, query: &MemoryQuery) -> MemoryResult<Vec<MemoryMatch>> {
        let response = STMRepository::list_sessions(
            &pool(),
            &self.tenant_id,
            None,
            None,
            Some(query.limit as i32),
            Some(query.offset as i32),
        )
        .await
        .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(response
            .sessions
            .into_iter()
            .map(|s| {
                let sid = s.session_id.clone();
                MemoryMatch {
                    entry: MemoryEntry {
                        id: MemoryId::from_string(sid.clone()),
                        layer: LayerType::Stm,
                        content: MemoryContent::Json(serde_json::to_value(&s).unwrap_or_default()),
                        metadata: MemoryMetadata {
                            user_id: Some(s.user_id),
                            session_id: Some(sid),
                        ..Default::default()
                    },
                    created_at: 0,
                    updated_at: 0,
                },
                score: 1.0,
                highlights: vec![],
            }
            })
            .collect())
    }

    async fn update(&self, _id: &MemoryId, _entry: MemoryEntry) -> MemoryResult<()> {
        Err(MemoryError::InvalidOperation(
            "STM sessions are immutable".to_string(),
        ))
    }

    async fn delete(&self, id: &MemoryId) -> MemoryResult<()> {
        STMRepository::delete_session(&pool(), &self.tenant_id, id.as_str())
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(())
    }

    async fn stats(&self) -> MemoryResult<LayerStats> {
        let count = crate::db::stm::count_active_sessions(&pool())
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(LayerStats {
            entry_count: count as usize,
            size_bytes: 0,
            avg_access_count: 0.0,
        })
    }
}

// ============================================================================
// KG Database Layer
// ============================================================================

pub struct DatabaseKgLayer {
    tenant_id: TenantId,
}

impl DatabaseKgLayer {
    pub fn new(tenant_id: TenantId) -> Self {
        Self { tenant_id }
    }
}

#[async_trait::async_trait]
impl MemoryLayer for DatabaseKgLayer {
    fn layer_type(&self) -> LayerType {
        LayerType::Kg
    }

    async fn store(&self, entry: MemoryEntry) -> MemoryResult<MemoryId> {
        let (name, entity_type, description) = extract_entity_info(&entry.content)?;
        let entity_id = KGRepository::create_entity(
            &self.tenant_id,
            &name,
            &entity_type,
            Some(&description),
            None,
            None,
            None,
            None,
            0.5,
        )
        .await
        .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(MemoryId::from_string(entity_id))
    }

    async fn retrieve(&self, id: &MemoryId) -> MemoryResult<MemoryEntry> {
        let entity = KGRepository::get_entity_by_id(&pool(), &self.tenant_id, id.as_str())
            .await
            .map_err(|e| MemoryError::Storage(e.to_string()))?;
        match entity {
            Some(e) => Ok(MemoryEntry {
                id: MemoryId::from_string(e.entity_id),
                layer: LayerType::Kg,
                content: MemoryContent::Json(serde_json::json!({
                    "name": e.entity_name,
                    "type": e.entity_type,
                    "description": e.description
                })),
                metadata: MemoryMetadata::default(),
                created_at: chrono::DateTime::parse_from_rfc3339(&e.created_at)
                    .map(|d| d.timestamp())
                    .unwrap_or(0),
                updated_at: chrono::DateTime::parse_from_rfc3339(&e.updated_at)
                    .map(|d| d.timestamp())
                    .unwrap_or(0),
            }),
            None => Err(MemoryError::NotFound(format!(
                "KG entity not found: {}",
                id.as_str()
            ))),
        }
    }

    async fn search(&self, query: &MemoryQuery) -> MemoryResult<Vec<MemoryMatch>> {
        let response = KGRepository::list_entities(
            &pool(),
            &self.tenant_id,
            None,
            Some(query.limit as i32),
            Some(query.offset as i32),
        )
        .await
        .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(response
            .entities
            .into_iter()
            .map(|e| MemoryMatch {
                entry: MemoryEntry {
                    id: MemoryId::from_string(e.entity_id),
                    layer: LayerType::Kg,
                    content: MemoryContent::Json(serde_json::json!({
                        "name": e.entity_name,
                        "type": e.entity_type,
                        "description": e.description
                    })),
                    metadata: MemoryMetadata::default(),
                    created_at: 0,
                    updated_at: 0,
                },
                score: 1.0,
                highlights: vec![],
            })
            .collect())
    }

    async fn update(&self, _id: &MemoryId, _entry: MemoryEntry) -> MemoryResult<()> {
        Err(MemoryError::InvalidOperation(
            "KG entity update is not yet implemented via the database layer".to_string(),
        ))
    }

    async fn delete(&self, _id: &MemoryId) -> MemoryResult<()> {
        Err(MemoryError::InvalidOperation(
            "KG entity delete is not yet implemented via the database layer".to_string(),
        ))
    }

    async fn stats(&self) -> MemoryResult<LayerStats> {
        let response = KGRepository::list_entities(
            &pool(),
            &self.tenant_id,
            None,
            Some(1),
            Some(0),
        )
        .await
        .map_err(|e| MemoryError::Storage(e.to_string()))?;
        Ok(LayerStats {
            entry_count: response.total as usize,
            size_bytes: 0,
            avg_access_count: 0.0,
        })
    }
}

// ============================================================================
// Helpers
// ============================================================================

fn text_content(content: &MemoryContent) -> MemoryResult<String> {
    match content {
        MemoryContent::Text(s) => Ok(s.clone()),
        MemoryContent::Json(j) => Ok(j.to_string()),
        _ => Err(MemoryError::InvalidOperation(
            "only text/json content is supported".to_string(),
        )),
    }
}

fn extract_entity_info(content: &MemoryContent) -> MemoryResult<(String, String, String)> {
    match content {
        MemoryContent::Json(j) => {
            let name = j.get("name").and_then(|v| v.as_str()).unwrap_or("unknown");
            let etype = j.get("type").and_then(|v| v.as_str()).unwrap_or("concept");
            let desc = j.get("description").and_then(|v| v.as_str()).unwrap_or("");
            Ok((name.to_string(), etype.to_string(), desc.to_string()))
        }
        MemoryContent::Text(t) => Ok((t.clone(), "concept".to_string(), String::new())),
        _ => Err(MemoryError::InvalidOperation(
            "KG layer only supports text/json content".to_string(),
        )),
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn text_content_extracts_text() {
        let content = MemoryContent::Text("hello".to_string());
        assert_eq!(text_content(&content).unwrap(), "hello");
    }

    #[test]
    fn text_content_rejects_binary() {
        let content = MemoryContent::Binary(vec![1, 2, 3]);
        assert!(text_content(&content).is_err());
    }

    #[test]
    fn database_ltm_layer_reports_ltm_type() {
        let tenant = TenantId::from_string("t");
        let layer = DatabaseLtmLayer::new(tenant);
        assert_eq!(layer.layer_type(), LayerType::Ltm);
    }

    #[test]
    fn database_stm_layer_reports_stm_type() {
        let tenant = TenantId::from_string("t");
        let layer = DatabaseStmLayer::new(tenant);
        assert_eq!(layer.layer_type(), LayerType::Stm);
    }

    #[test]
    fn database_kg_layer_reports_kg_type() {
        let tenant = TenantId::from_string("t");
        let layer = DatabaseKgLayer::new(tenant);
        assert_eq!(layer.layer_type(), LayerType::Kg);
    }
}